name: Tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r django_template/requirements/development.txt
    - name: Run tests and check for coverage
      run: |
        cd django_template
        coverage run manage.py test
        coverage xml -i
        export CODECOV_TOKEN=${{ secrets.codecov_token }}
        coverage report
        bash <(curl -s https://codecov.io/bash) -cF unit
        coverage run $(which behave) apps/**/tests/integration
        coverage xml -i
        coverage report
        bash <(curl -s https://codecov.io/bash) -cF integration
