name: Security

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r django_template/requirements/development.txt
    - name: Run package auditing
      run: |
        python -m safety check
    - name: Run security linter
      run: |
        python -m bandit -c .bandit-config.yml -r django_template/**
